# Generated by Django 3.2.1 on 2021-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('stateOrProvince', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('orderNumber', models.CharField(max_length=33)),
            ],
        ),
    ]
