# Generated by Django 3.2.1 on 2021-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatDrink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantityOfDrinks',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
